import { IntentionTemplate } from "./types"

export const FINANCE_TEMPLATES: IntentionTemplate[] = [
  {
    id: "track-expenses",
    category: "Finance",
    when: "Večer před spaním",
    action: "zapíšu si všechny dnešní výdaje",
    context: "do aplikace",
    habit: "Sledování výdajů",
  },
  {
    id: "weekly-budget-review",
    category: "Finance",
    when: "V neděli večer",
    action: "zkontroluji týdenní rozpočet",
    context: "v Excelu",
    habit: "Týdenní budget review",
  },
  {
    id: "auto-savings",
    category: "Finance",
    when: "Když dostanu výplatu",
    action: "přesunu 10% na spořicí účet",
    context: "v bance",
    habit: "Automatické spoření",
  },
  {
    id: "no-impulse-buy",
    category: "Finance",
    when: "Když chci něco koupit",
    action: "počkám 24 hodin",
    context: "pravidlo jednoho dne",
    habit: "Žádné impulzivní nákupy",
  },
  {
    id: "monthly-net-worth",
    category: "Finance",
    when: "První den v měsíci",
    action: "spočítám si čisté jmění",
    context: "v tabulce",
    habit: "Měsíční net worth",
  },
  {
    id: "invoice-tracking",
    category: "Finance",
    when: "Každé pondělí",
    action: "zkontroluju nezaplacené faktury",
    context: "v účetním systému",
    habit: "Správa faktur",
  },
  {
    id: "financial-reading",
    category: "Finance",
    when: "O víkendu",
    action: "přečtu si článek o financích",
    context: "na blogu",
    habit: "Finanční vzdělávání",
  },
  {
    id: "subscription-audit",
    category: "Finance",
    when: "Poslední den měsíce",
    action: "zkontroluji všechny předplatné",
    context: "a zruším nepotřebná",
    habit: "Audit předplatných",
  },
  {
    id: "price-comparison",
    category: "Finance",
    when: "Před nákupem",
    action: "porovnám ceny ve 3 obchodech",
    context: "online",
    habit: "Porovnání cen",
  },
  {
    id: "retirement-contribution",
    category: "Finance",
    when: "Po výplatě",
    action: "přispěju na důchodový účet",
    context: "v bance",
    habit: "Důchodové spoření",
  },
]
