import { IntentionTemplate } from "./types"

export const FITNESS_TEMPLATES: IntentionTemplate[] = [
  {
    id: "gym-bag",
    category: "Fitness",
    when: "Když se vrátím domů z práce",
    action: "obléknu si sportovní oblečení",
    context: "hned po příchodu",
    habit: "Večerní cvičení",
  },
  {
    id: "morning-run",
    category: "Fitness",
    when: "V 6:30 ráno",
    action: "jdu běhat 5 km",
    context: "v parku",
    habit: "Ranní běh",
  },
  {
    id: "pushups-daily",
    category: "Fitness",
    when: "Po probuzení",
    action: "udělám 20 kliků",
    context: "v ložnici",
    habit: "Ranní kliky",
  },
  {
    id: "yoga-morning",
    category: "Fitness",
    when: "Po snídani",
    action: "cvičím jógu 15 minut",
    context: "na podložce",
    habit: "Ranní jóga",
  },
  {
    id: "stairs-elevator",
    category: "Fitness",
    when: "Když vidím výtah",
    action: "půjdu po schodech",
    context: "v práci/domě",
    habit: "Chůze po schodech",
  },
  {
    id: "workout-playlist",
    category: "Fitness",
    when: "Když jdu cvičit",
    action: "pustím si motivační playlist",
    context: "v sluchátkách",
    habit: "Motivační hudba",
  },
  {
    id: "stretching-bed",
    category: "Fitness",
    when: "Před spaním",
    action: "protáhnu celé tělo 10 minut",
    context: "vedle postele",
    habit: "Večerní strečink",
  },
  {
    id: "plank-challenge",
    category: "Fitness",
    when: "Po čištění zubů",
    action: "udržím plank 60 sekund",
    context: "v koupelně",
    habit: "Denní plank",
  },
  {
    id: "active-commute",
    category: "Fitness",
    when: "Cestou do práce",
    action: "vystoupím o zastávku dříve a dojdu pěšky",
    context: "venku",
    habit: "Aktivní dojíždění",
  },
  {
    id: "water-workout",
    category: "Fitness",
    when: "Během cvičení",
    action: "vypiju 0.5 l vody",
    context: "u lahve",
    habit: "Hydratace při cvičení",
  },
]
