import { IntentionTemplate } from "./types"

export const PRACE_TEMPLATES: IntentionTemplate[] = [
  {
    id: "sit-at-desk-planner",
    category: "Práce",
    when: "Když se posadím k počítači",
    action: "otevřu denní plánovač",
    context: "na ploše",
    habit: "Denní plánování",
  },
  {
    id: "pomodoro-break",
    category: "Práce",
    when: "Po 25 minutách práce",
    action: "udělám 5minutovou pauzu",
    context: "mimo obrazovku",
    habit: "Pomodoro pauzy",
  },
  {
    id: "lunch-break-walk",
    category: "Práce",
    when: "V poledne",
    action: "jdu na 15minutovou procházku",
    context: "venku",
    habit: "Polední procházka",
  },
  {
    id: "inbox-zero",
    category: "Práce",
    when: "Na začátku pracovního dne",
    action: "zpracuji všechny emaily",
    context: "do 30 minut",
    habit: "Inbox Zero",
  },
  {
    id: "deep-work-block",
    category: "Práce",
    when: "Ráno v 9:00",
    action: "začnu 2 hodiny deep work",
    context: "bez notifikací",
    habit: "Deep Work",
  },
  {
    id: "stand-up-meeting",
    category: "Práce",
    when: "Každou celou hodinu",
    action: "vstanu a protáhnu se",
    context: "u stolu",
    habit: "Hodinové protažení",
  },
  {
    id: "prioritize-tasks",
    category: "Práce",
    when: "Na začátku dne",
    action: "označím 3 nejdůležitější úkoly",
    context: "v task manageru",
    habit: "MIT (Most Important Tasks)",
  },
  {
    id: "end-of-day-review",
    category: "Práce",
    when: "Před odchodem z práce",
    action: "zapíšu si, co jsem dokončil",
    context: "do deníku",
    habit: "Denní review",
  },
  {
    id: "calendar-blocking",
    category: "Práce",
    when: "V neděli večer",
    action: "naplánuji si celý nadcházející týden",
    context: "v kalendáři",
    habit: "Týdenní plánování",
  },
  {
    id: "no-phone-work",
    category: "Práce",
    when: "Když začnu pracovat",
    action: "dám telefon do šuplíku",
    context: "mimo dosah",
    habit: "Fokus bez telefonu",
  },
]
