import { IntentionTemplate } from "./types"

export const RANO_TEMPLATES: IntentionTemplate[] = [
  {
    id: "wake-up-water",
    category: "Ráno",
    when: "Když vstanu z postele",
    action: "napiju se sklenici vody",
    context: "v kuchyni",
    habit: "Pít vodu",
  },
  {
    id: "wake-up-stretch",
    category: "Ráno",
    when: "Když vstanu z postele",
    action: "udělám 5 minut strečinku",
    context: "v ložnici",
    habit: "Ranní strečink",
  },
  {
    id: "after-coffee-exercise",
    category: "Ráno",
    when: "Poté co vypiju ranní kávu",
    action: "jdu na 10minutovou procházku",
    context: "venku",
    habit: "Ranní procházka",
  },
  {
    id: "breakfast-vitamins",
    category: "Ráno",
    when: "Když si připravím snídani",
    action: "vezmu si vitamíny",
    context: "u jídelního stolu",
    habit: "Vitamíny",
  },
  {
    id: "morning-meditation",
    category: "Ráno",
    when: "Před snídaní",
    action: "medituju 10 minut",
    context: "v klidné místnosti",
    habit: "Ranní meditace",
  },
  {
    id: "morning-journal",
    category: "Ráno",
    when: "U ranní kávy",
    action: "napíšu 3 priority dne",
    context: "do deníku",
    habit: "Ranní plánování",
  },
  {
    id: "cold-shower",
    category: "Ráno",
    when: "Po probuzení",
    action: "dám si studenou sprchu 30 sekund",
    context: "v koupelně",
    habit: "Studená sprcha",
  },
  {
    id: "morning-protein",
    category: "Ráno",
    when: "Po cvičení",
    action: "dám si proteinovou snídani",
    context: "do 30 minut",
    habit: "Proteinová snídaně",
  },
  {
    id: "bed-making",
    category: "Ráno",
    when: "Ihned po vstání",
    action: "ustelu postel",
    context: "v ložnici",
    habit: "Uklizená postel",
  },
  {
    id: "morning-affirmation",
    category: "Ráno",
    when: "Při čištění zubů",
    action: "řeknu si 3 pozitivní afirmace",
    context: "před zrcadlem",
    habit: "Ranní afirmace",
  },
]
