import { IntentionTemplate } from "./types"

export const STRES_TEMPLATES: IntentionTemplate[] = [
  {
    id: "feel-stressed",
    category: "Stres",
    when: "Když se cítím stresovaný",
    action: "udělám 5 hlubokých nádechů",
    context: "kdekoliv",
    habit: "Dechová cvičení",
  },
  {
    id: "overwhelmed",
    category: "Stres",
    when: "Když se cítím zahlcený",
    action: "napíšu si všechny úkoly na papír",
    context: "do notebooku",
    habit: "Brain dump",
  },
  {
    id: "box-breathing",
    category: "Stres",
    when: "Před důležitou schůzkou",
    action: "udělám 4-4-4-4 dechové cvičení",
    context: "v klidu",
    habit: "Box breathing",
  },
  {
    id: "progressive-relaxation",
    category: "Stres",
    when: "Když cítím napětí",
    action: "postupně uvolním všechny svaly",
    context: "vsedě/vleže",
    habit: "Progresivní relaxace",
  },
  {
    id: "nature-break",
    category: "Stres",
    when: "Během stresného dne",
    action: "jdu na 10 minut ven",
    context: "do přírody",
    habit: "Příroda jako únik",
  },
  {
    id: "music-calm",
    category: "Stres",
    when: "Když jsem nervózní",
    action: "pustím si uklidňující hudbu",
    context: "se sluchátky",
    habit: "Relaxační hudba",
  },
  {
    id: "stress-journal",
    category: "Stres",
    when: "Když se cítím úzkostně",
    action: "napíšu si, co mě trápí",
    context: "do deníku",
    habit: "Deník emocí",
  },
  {
    id: "call-friend",
    category: "Stres",
    when: "Když potřebuju podporu",
    action: "zavolám kamarádovi",
    context: "na telefonu",
    habit: "Sociální podpora",
  },
  {
    id: "cold-water-face",
    category: "Stres",
    when: "Při panické atace",
    action: "omyju si tvář studenou vodou",
    context: "v koupelně",
    habit: "Studená voda na tvář",
  },
  {
    id: "gratitude-stress",
    category: "Stres",
    when: "Když se cítím negativně",
    action: "vyjmenuji 3 věci, za které jsem vděčný",
    context: "nahlas",
    habit: "Vděčnost při stresu",
  },
]
