import { IntentionTemplate } from "./types"

export const UCENI_TEMPLATES: IntentionTemplate[] = [
  {
    id: "commute-podcast",
    category: "Učení",
    when: "Když jdu do práce",
    action: "pustím si vzdělávací podcast",
    context: "v autě/MHD",
    habit: "Vzdělávací podcasty",
  },
  {
    id: "duolingo",
    category: "Učení",
    when: "Když čekám na kávu",
    action: "udělám jednu lekci v Duolingu",
    context: "na telefonu",
    habit: "Učení jazyka",
  },
  {
    id: "read-before-bed",
    category: "Učení",
    when: "Před spaním",
    action: "přečtu si 20 stran knihy",
    context: "v posteli",
    habit: "Denní čtení",
  },
  {
    id: "flashcards-morning",
    category: "Učení",
    when: "U ranní kávy",
    action: "procvičím si flashcards 10 minut",
    context: "v Anki",
    habit: "Opakování flashcards",
  },
  {
    id: "online-course",
    category: "Učení",
    when: "Po večeři",
    action: "udělám jednu lekci online kurzu",
    context: "u počítače",
    habit: "Online vzdělávání",
  },
  {
    id: "ted-talk",
    category: "Učení",
    when: "Během oběda",
    action: "pustím si jeden TED talk",
    context: "na YouTube",
    habit: "TED talks",
  },
  {
    id: "writing-practice",
    category: "Učení",
    when: "Ráno po snídani",
    action: "napíšu 500 slov",
    context: "do deníku/blogu",
    habit: "Denní psaní",
  },
  {
    id: "skill-practice",
    category: "Učení",
    when: "Večer v 19:00",
    action: "cvičím programování 30 minut",
    context: "u počítače",
    habit: "Programování",
  },
  {
    id: "news-summary",
    category: "Učení",
    when: "U ranní kávy",
    action: "přečtu si souhrn zpráv",
    context: "v aplikaci",
    habit: "Denní zprávy",
  },
  {
    id: "brain-training",
    category: "Učení",
    when: "Před spaním",
    action: "udělám brain training hru",
    context: "na telefonu",
    habit: "Trénink mozku",
  },
]
