import { IntentionTemplate } from "./types"

export const VECER_TEMPLATES: IntentionTemplate[] = [
  {
    id: "dinner-gratitude",
    category: "Večer",
    when: "Po večeři",
    action: "zapíšu si 3 věci, za které jsem vděčný",
    context: "do deníku",
    habit: "Deník vděčnosti",
  },
  {
    id: "evening-reading",
    category: "Večer",
    when: "V 21:00",
    action: "čtu knihu 20 minut",
    context: "v křesle",
    habit: "Večerní čtení",
  },
  {
    id: "phone-away",
    category: "Večer",
    when: "V 22:00",
    action: "dám telefon do letadlového režimu",
    context: "mimo ložnici",
    habit: "Digital detox",
  },
  {
    id: "sleep-routine",
    category: "Večer",
    when: "30 minut před spaním",
    action: "udělám relaxační dechové cvičení",
    context: "v posteli",
    habit: "Relaxace před spaním",
  },
  {
    id: "evening-walk",
    category: "Večer",
    when: "Po večeři",
    action: "jdu na 20minutovou procházku",
    context: "v okolí",
    habit: "Večerní procházka",
  },
  {
    id: "skincare-routine",
    category: "Večer",
    when: "Před spaním",
    action: "udělám večerní péči o pleť",
    context: "v koupelně",
    habit: "Večerní péče o pleť",
  },
  {
    id: "tomorrow-prep",
    category: "Večer",
    when: "Před spaním",
    action: "připravím si oblečení na zítra",
    context: "v ložnici",
    habit: "Příprava na zítřek",
  },
  {
    id: "evening-tea",
    category: "Večer",
    when: "V 20:00",
    action: "uvařím si bylinný čaj",
    context: "v kuchyni",
    habit: "Večerní čaj",
  },
  {
    id: "screen-free-hour",
    category: "Večer",
    when: "Hodinu před spaním",
    action: "vypnu všechny obrazovky",
    context: "doma",
    habit: "Screen-free hodina",
  },
  {
    id: "evening-reflection",
    category: "Večer",
    when: "Před spaním",
    action: "zhodnotím, co šlo dobře dnes",
    context: "do deníku",
    habit: "Večerní reflexe",
  },
]
