import { IntentionTemplate } from "./types"

export const ZDRAVI_TEMPLATES: IntentionTemplate[] = [
  {
    id: "water-hour",
    category: "Zdraví",
    when: "Každou celou hodinu",
    action: "napiju se vody",
    context: "u stolu",
    habit: "Pravidelné pití",
  },
  {
    id: "standing-desk",
    category: "Zdraví",
    when: "Po hodině sezení",
    action: "přepnu na standing desk",
    context: "v kanceláři",
    habit: "Střídání pozic",
  },
  {
    id: "eye-rest",
    category: "Zdraví",
    when: "Po 20 minutách u počítače",
    action: "podívám se 20 sekund do dálky",
    context: "z okna",
    habit: "Pravidlo 20-20-20",
  },
  {
    id: "healthy-snack",
    category: "Zdraví",
    when: "Když dostanu hlad",
    action: "sním ovoce nebo ořechy",
    context: "místo sladkostí",
    habit: "Zdravé svačiny",
  },
  {
    id: "posture-check",
    category: "Zdraví",
    when: "Při sezení",
    action: "zkontroluju si správné držení těla",
    context: "každých 30 minut",
    habit: "Správné držení těla",
  },
  {
    id: "dental-floss",
    category: "Zdraví",
    when: "Po čištění zubů večer",
    action: "použiju zubní nit",
    context: "v koupelně",
    habit: "Zubní nit",
  },
  {
    id: "sunlight-morning",
    category: "Zdraví",
    when: "Do 30 minut po probuzení",
    action: "vystavím se slunečnímu světlu",
    context: "u okna/venku",
    habit: "Ranní sluneční světlo",
  },
  {
    id: "meal-prep-sunday",
    category: "Zdraví",
    when: "V neděli odpoledne",
    action: "připravím si jídla na celý týden",
    context: "v kuchyni",
    habit: "Meal prep",
  },
  {
    id: "no-sugar-coffee",
    category: "Zdraví",
    when: "Když si dělám kávu",
    action: "nedám si tam cukr",
    context: "u kávovaru",
    habit: "Káva bez cukru",
  },
  {
    id: "bedtime-consistent",
    category: "Zdraví",
    when: "V 22:30",
    action: "jdu spát",
    context: "každý den stejně",
    habit: "Pravidelný spánek",
  },
]
